config/routes.rb
Rails.application.routes.draw do
  get 'message/create'
  root 'pages#home'

  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show', as: 'users'
  get '/selling_orders', to: 'orders#selling_orders'
  get '/buying_orders', to: 'orders#buying_orders'
  get '/orders/:id', to: 'orders#show', as: 'order_detail'
  get '/all_requests', to: 'requests#list'
  get '/request_offers/:id', to: 'requests#offers', as: 'request_offers'
  get '/my_offers', to: 'requests#my_offers'
  get '/search', to: 'pages#search'
  get '/calendar', to: 'pages#calendar'
  get '/plans', to: 'pages#plans'
  get '/settings/payment', to: 'users#payment', as: 'settings_payment'
  get '/settings/payout', to: 'users#payout', as: 'settings_payout'
  get '/gigs/:id/checkout/:pricing_type', to: 'gigs#checkout', as: 'checkout'
  get '/earnings', to: 'users#earnings', as: 'earnings'
  get '/conversations', to: 'conversations#list', as: 'conversations'
  get '/conversations/:id', to: 'conversations#show', as: 'conversation_detail'
  
  post '/users/edit', to: 'users#update'
  post '/offers', to: 'offers#create'
  post '/reviews', to: 'reviews#create'
  post '/settings/payment', to: 'users#update_payment', as: 'update_payment'
  post '/settings/payout', to: 'users#update_payout', as: 'update_payout'
  post '/users/withdraw', to: 'users#withdraw', as: 'withdraw'
  post '/messages', to: 'messages#create'
  post '/comments', to: 'comments#create'
  post '/subscribe', to: 'subscriptions#subscribe'
  post '/webhook', to: 'subscriptions#webhook'

  put 'orders/:id/complete', to: 'orders#complete', as: 'complete_order'
  put '/offers/:id/accept', to: 'offers#accept', as: 'accept_offer'
  put '/offers/:id/reject', to: 'offers#reject', as: 'reject_offer'

  delete '/gigs/:id/deactivate', to: 'gigs#deactivate', as: 'deactivate_gig'
  delete '/users/remove_subscription', to: 'users#remove_subscription', as: 'remove_subscription'

  mount ActionCable.server => '/cable'

  resources :gigs do
    member do
      delete :delete_photo
      post :upload_photo
    end
    resources :orders, only: [:create]
  end

  resources :requests

  devise_for :users, 
              path: '', 
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_one_attached :avatar
  has_many :gigs
  has_many :requests
  has_many :offers
  
  has_many :buying_orders, foreign_key: "buyer_id", class_name: "Order"
  has_many :selling_orders, foreign_key: "seller_id", class_name: "Order"

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :lastseenable

  validates :full_name, presence: true, length: {maximum: 50}

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first

    if user 
      if !user.provider
        user.update(uid: auth.uid, provider: auth.provider, image: auth.info.image)
      end
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.full_name = auth.info.name   # assuming the user model has a name
        user.image = auth.info.image # assuming the user model has an image

        user.uid = auth.uid
        user.provider = auth.provider
      end
    end
  end

  def online?
    return !last_seen.nil? && ((last_seen + 10.minutes) > Time.now)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def dashboard 
    @subscription = Subsription.find_by_user_id(current_user.id)
    if @subscription.present?
      @plan = Stripe::Plan.retrieve(@subscription.plan_id)
    end
  end

  def show
    @user = User.find(params[:id])
    @reviews = Review.where(seller_id: params[:id]).order("created_at desc")
  end

  def update
    @user = current_user
    if @user.update(current_users_params)
      flash[:notice] = "Sauvé."
    else
      flash[:alert] = "Impossible de mettre à jour."
    end
    redirect_to dashboard_path
  end

  def update_payment
    if !current_user.stripe_id
      customer = Stripe::Customer.create(
        email: current_user.email,
        source: params[:stripeToken]
      )
    else
      customer = Stripe::Customer.update(
        current_user.stripe_id,
        source: params[:stripeToken]
      )
    end

    if current_user.update(stripe_id: customer.id, stripe_last_4: customer.sources.data.first['last4'])
      flash[:notice] = "La nouvelle carte est enregistrée"
    else
      flash[:alert] = "Carte non valide"
    end
    redirect_to request.referrer
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to request.referrer
  end

  def update_payout
    if current_user.update(paypal: params['paypal'])
      flash[:notice] = "Mise à jour du paiement réussie"
    else
      flash[:error] = "Quelque chose n'a pas fonctionné"
    end
    redirect_to request.referrer
  end

  def earnings
    @net_income = (Transaction.where("seller_id = ?", current_user.id).sum(:amount) / 1.1).round(2)

    @withdrawn = Transaction.where("buyer_id = ? AND status = ? and transaction_type = ?", 
                    current_user.id, 
                    Transaction.statuses[:approved],
                    Transaction.transaction_types[:withdraw]
                  ).sum(:amount)

    @pending = Transaction.where("buyer_id = ? AND status = ? and transaction_type = ?", 
                current_user.id, 
                Transaction.statuses[:pending],
                Transaction.transaction_types[:withdraw]
              ).sum(:amount)

    @purchased = Transaction.where("buyer_id = ? AND source_type = ? and transaction_type = ?", 
                  current_user.id, 
                  Transaction.source_types[:system],
                  Transaction.transaction_types[:trans]
                ).sum(:amount)

    @withdrawable = current_user.wallet

    @transactions = Transaction.where("seller_id = ? OR (buyer_id = ? AND source_type = ?)", 
                      current_user.id,
                      current_user.id,
                      Transaction.source_types[:system]
                    ).page(params[:page])
  end

  def withdraw
    amount = params[:amount].to_i
    is_pending_withdraw = Transaction.exists?(buyer_id: current_user.id, 
                                              status: Transaction.statuses[:pending], 
                                              transaction_type: Transaction.transaction_types[:withdraw]
                                             )
    
    if amount <= 0
      flash[:alert] = "Montant non valide"
    elsif amount > current_user.wallet
      flash[:alert] = "Vous demandez plus que ce que vous avez"
    elsif !is_pending_withdraw.blank?
      flash[:alert] = "Vous avez une demande de retrait en cours"
    else
      transaction = Transaction.new
      transaction.status = Transaction.statuses[:pending]
      transaction.transaction_type = Transaction.transaction_types[:withdraw]
      transaction.source_type = Transaction.source_types[:system]
      transaction.buyer = current_user
      transaction.amount = amount

      if transaction.save
        flash[:notice] = "Demande de retrait créée avec succès"
      else
        flash[:alert] = "Impossible de créer une demande"
      end
    end

    redirect_to request.referrer
  end

  def remove_subscription
    @subscription = Subsription.find_by_user_id(current_user.id)

    if @subscription.present? && @subscription.sub_id
      Stripe::Subscription.cancel(@subscription.sub_id)
      # Supprimer l'abonnement local
      Subsription.destroy(@subscription.id)
      return redirect_to request.referrer, notice: "Votre abonnement est annulé"
    end
    return redirect_to request.referrer, alert: "Impossible d'annuler votre abonnement"
  end

  private
  def current_users_params
    params.require(:user).permit(:from, :about, :status, :language, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/dashboard.html.erb
<section class="section">
    <div class="container">
        <div class="columns">
        
            <!-- LEFT SIDE -->
            <div class="column is-one-third">
                <div class="columns is-multiline">

                    <!-- Top Card -->
                    <div class="column is-full">
                        <div class="card">

                            <!-- Avatar -->
                            <div class="card-content is-horizontal-center is-flex">
                                <figure class="image is-128x128 avatar <%= current_user.online? ? 'online' : 'offline' %>">
                                    <%= image_tag avatar_url(current_user), class: "is-rounded" %>
                                </figure>
                            </div>
                            
                            <div class="card-content">

                                <!-- Upload Button -->
                                <div class="content has-text-centered">
                                    <p class="title is-5"><%= current_user.full_name %></p>

                                    <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post do |f| %>
                                      <div class="file">
                                        <label class="button is-primary is-outlined is-fullwidth">
                                            <%= f.file_field :avatar, class: "file-input", onchange: "this.form.submit();" %>
                                            <i class="fas fa-upload"></i>&nbsp;&nbsp;&nbsp; Charger un avatar
                                        </label>
                                        </div>
                                    <% end %>
                                </div>
                                <hr class="h-10">
                                
                                <!-- Member -->
                                <article>
                                    <div class="media">
                                        <div class="media-content">Membre depuis</div>
                                        <div class="media-right">
                                            <strong><%= current_user.created_at.strftime('%b %Y') %></strong>
                                        </div>
                                    </div>
                                </article>
                                <hr class="h-10">
                                
                                <!-- De -->
                                <article>
                                    <div class="media">
                                        <div class="media-content">De</div>
                                        <div class="media-right">
                                            <strong><%= current_user.from %></strong> <i class="toggle far fa-edit" aria-controls="user-from"></i>
                                        </div>
                                    </div>

                                    <div class="content">
                                        <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: 'user-from', class: 'is-hidden'} do |f| %>
                                            <div class="field">
                                                <%= f.text_field :from, autofocus: true, autcomplete: 'form', class: 'input' %>
                                            </div>
                                            <a class="toggle button is-light" aria-controls="user-from">Annuler</a>
                                            <%= f.submit "Sauvegarder", class: "button is-danger" %>
                                        <% end %>
                                    </div>
                                </article>                                
                                <hr class="h-10">       

                                <!-- Subscription -->
                                <% if @subscription.present? %>
                                    <article >
                                        <div class="media">
                                            <div class="media-content">Abonnement</div>
                                            <div class="media-right">
                                                <strong><% if @plan %> <%= @plan.nickname %> <% end %></strong>&nbsp;<i class="toggle far fa-edit" aria-controls="user-subscription"></i>
                                            </div>
                                        </div>

                                        <div class="content">
                                            <%= form_with url: remove_subscription_path, method: :delete, html: {id: 'user-subscription', class: 'is-hidden'} do |f| %>
                                                <small>Expire le : <%= @subscription.expired_at %> </small>
                                                <%= f.submit "Annuler mon abonnement", class: "button is-danger is-fullwidth m-t-20" %>
                                            <% end %>
                                        </div>
                                    </article>
                                <% end %>
                            </div>
                        </div>
                    </div>

                    <!-- Bottom Card -->
                    <div class="column is-full">
                        <div class="card">
                            <div class="card-content">

                                <!-- About -->
                                <article>
                                    <div class="media">
                                        <div class="media-content">
                                            <p>
                                                <strong>À propos de vous</strong>
                                                <br/>
                                                <%= current_user.about %>
                                            </p>
                                        </div>
                                        <div class="media-right">
                                            <i class="toggle far fa-edit" aria-controls="user-about"></i>
                                        </div>
                                    </div>

                                    <div class="content">
                                        <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: 'user-about', class: 'is-hidden'} do |f| %>
                                            <div class="field">
                                                <%= f.text_area :about, autofocus: true, autcomplete: 'form', class: 'input' %>
                                            </div>
                                            <a class="toggle button is-light" aria-controls="user-about">Annuler</a>
                                            <%= f.submit "Sauvegarder", class: "button is-danger" %>
                                        <% end %>
                                    </div>
                                </article>
                                <hr class="h-10">

                                <!-- Language -->
                                <article>
                                    <div class="media">
                                        <div class="media-content">
                                            <p>
                                                <strong>Langue</strong>
                                                <br/>
                                                <%= current_user.language %>
                                            </p>
                                        </div>
                                        <div class="media-right">
                                            <i class="toggle far fa-edit" aria-controls="user-language"></i>
                                        </div>
                                    </div>

                                    <div class="content">
                                        <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: 'user-language', class: 'is-hidden'} do |f| %>
                                            <div class="field">
                                                <%= f.text_field :language, autofocus: true, autcomplete: 'form', class: 'input' %>
                                            </div>
                                            <a class="toggle button is-light" aria-controls="user-language">Annuler</a>
                                            <%= f.submit "Sauvegarder", class: "button is-danger" %>
                                        <% end %>
                                    </div>
                                </article>
                                <hr class="h-10">
                                

                            </div>
                        </div>
                    </div>

                </div>
            </div>

            <!-- RIGHT SIDE -->
            <div class="column">
                <div class="columns is-multiline">

                    <!-- Create New Gig -->
                    <div class="column is-one-third has-text-centered">
                        <%= link_to new_gig_path do %>
                            <div class="card">

                                <div class="card-image card-content is-horizontal-center is-flex ">
                                    <figure class="image is-128x128 ">
                                        <%= image_tag 'icon_add.png' %>
                                    </figure>
                                </div>

                                <div class="card-content">
                                    <strong>Créer un nouveau service</strong>
                                </div>    

                            </div>
                        <% end %>
                    </div>

                    <!-- Sample Gig -->
                    <% current_user.gigs.each do |gig| %>

                        <div class="column is-one-third">
                            <div class="card">

                                <div class="card-image">
                                    <figure class="image is-4by3">
                                        <%= image_tag gig_cover(gig) %>
                                    </figure>
                                </div>

                                <div class="card-content p-t-5 p-b-5">
                                    <p class="subtitle is-6 m-b-5"><%= link_to gig.title, gig_path(gig) %></p>
                                    <span class="star-review"><i class="fa fa-star"></i>
                                        <%= gig.average_rating %> 
                                        <span class="has-text-primary">(<%= gig.reviews.count %>)</span>
                                    </span>    
                                    <br/>
                                    <!-- Edition & désactivation -->                                 
                                    <div>
                                        <a href="<%= edit_gig_path(gig) %>" class="button is-light is-small">Éditer</a>

                                        <!-- Si le gig est activé -->
                                        <% if gig.active? %>
                                            <!-- Désactiver -->
                                            <%= link_to deactivate_gig_path(gig), method: :delete, data: { confirm: 'Êtes-vous sûr ?' }, class: "button is-danger is-small" do %>
                                                Désactiver
                                            <% end %>
                                        <% end %>
                                        
                                    </div>
                                </div>

                                <footer class="card-footer">
                                    <% basic_price = gig.pricings.find{ |p| p.pricing_type == 'basic' } %>
                                    <a class="has-text-danger is-block card-footer-item has-text-right">
                                        <% if !basic_price.nil? and !basic_price.price.nil? %>
                                            <span class="small-title">À PARTIR DE</span> 
                                            <strong>€<%= basic_price.price %></strong>  
                                        <% else %>
                                            <strong>
                                                <span class="small-title has-text-dark">PAS ENCORE DE PRIX</span>
                                            </strong>
                                        <% end %>                                         
                                    </a>
                                </footer>  
                                
                            </div>
                        </div>
                    <% end %>

                </div>
            </div>
        </div>
    </div>
</section>

app/views/users/earnings.html.erb
<section class="section">
    <div class="container">
        <p class="title">Revenus</p>

        <div class="card">
            <div class="card-content">
                <div class="columns has-text-centered">
                    <div class="column">
                        Revenu net
                        <p class="is-size-4">€<%= @net_income %></p>
                    </div>
                    <div class="column">
                        Retiré
                        <p class="is-size-4">€<%= @withdrawn %></p>
                    </div>
                    <div class="column">
                        Utilisé pour les achats
                        <p class="is-size-4">€<%= @purchased %></p>
                    </div>
                    <div class="column">
                        En attente d'autorisation
                        <p class="is-size-4">€<%= @pending %></p>
                    </div>
                    <div class="column">
                        Disponible pour le retrait
                        <p class="is-size-4">€<%= @withdrawable %></p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Withdraw Form -->
        <div class="card m-t-20">
            <div class="card-content">
                <%= form_with url: withdraw_path do |f| %>
                    <div class="field is-grouped">
                        <div class="field is-horizontal" style="flex: 1;">
                            <div class="field-label is-normal">
                                <label class="label">Montant du retrait(€)</label>
                            </div>
                            <div class="field-body">
                                <div class="field">
                                    <%= f.number_field :amount, value: 0, class: "input" %>
                                </div>
                                <div class="field">
                                    <%= f.submit "Envoyer une demande", class: "button is-danger" %>
                                </div>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>

        <!-- Transaction List -->
        <div class="card m-t-20">
            <div class="card-header">
                <div class="card-header-title">Historique des transactions</div>
            </div>
            <div class="card-content">
                <table class="table is-fullwidth">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Source</th>
                            <th>Type</th>
                            <th>Statut</th>
                            <th>Montant</th>
                        </tr>
                    </thead>
                    
                    <tbody>
                        <% @transactions.each do |t| %>
                            <tr>
                                <td><%= t.created_at.strftime('%d, %b %Y') %></td>
                                <td><%= t.gig ? t.gig.title : "Montant du retrait" %></td>
                                <td><%= t.transaction_type %></td>
                                <td><span class="tag"><%= t.status %></span></td>
                                <td>
                                    <span class="<%= current_user.id == t.buyer_id ? 'has-text-danger' : 'has-text-success' %>">
                                        <%= current_user.id == t.buyer_id ? '-' : '+' %>
                                        €<%= current_user.id == t.buyer_id ? t.amount : (t.amount / 1.1).round(2) %>
                                    </span>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
                <%= paginate @transactions %>
            </div>
        </div>
    </div>
</section>

app/views/users/payment.html.erb
<style>
.StripeElement {
  box-sizing: border-box;

  height: 40px;

  padding: 10px 12px;

  border: 1px solid transparent;
  border-radius: 4px;
  background-color: white;

  box-shadow: 0 1px 3px 0 #e6ebf1;
  -webkit-transition: box-shadow 150ms ease;
  transition: box-shadow 150ms ease;
}

.StripeElement--focus {
  box-shadow: 0 1px 3px 0 #cfd7df;
}

.StripeElement--invalid {
  border-color: #fa755a;
}

.StripeElement--webkit-autofill {
  background-color: #fefde5 !important;
}
</style>

<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-8-tablet is-6-desktop is-6-widescreen">
                <p class="title has-text-centered">Mode de paiement</p>

                <% if current_user.stripe_last_4 %>
                    <div class="card">
                        <div class="card-header-title is-centered">
                            <%= "Votre carte actuelle : **** **** **** #{current_user.stripe_last_4}" %>
                        </div>
                    </div>
                <% end %>

                <%= form_with url: update_payment_path, local: true, id: "payment-form" do |f| %>
                    <div class="card form-row">
                        <div id="card-element">
                        <!-- A Stripe Element will be inserted here. -->
                        </div>

                        <!-- Used to display form errors. -->
                        <div id="card-errors" role="alert"></div>
                    </div>

                    <div class="field is-grouped is-grouped-centered">
                        <%= f.submit "#{current_user.stripe_id ? "Mettre à jour" : "Ajouter"}", class: "button is-primary m-t-20" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</section>

<script>
    // Create a Stripe client.
    var stripe = Stripe('<%= Rails.application.credentials[:development][:stripe][:STRIPE_PUBLIC_KEY] %>');

    // Create an instance of Elements.
    var elements = stripe.elements();

    // Custom styling can be passed to options when creating an Element.
    // (Note that this demo uses a wider set of styles than the guide below.)
    var style = {
        base: {
            color: '#32325d',
            fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
            fontSmoothing: 'antialiased',
            fontSize: '16px',
            '::placeholder': {
            color: '#aab7c4'
            }
        },
        invalid: {
            color: '#fa755a',
            iconColor: '#fa755a'
        }
    };

    // Create an instance of the card Element.
    var card = elements.create('card', {style: style});

    // Add an instance of the card Element into the `card-element` <div>.
    card.mount('#card-element');

    // Handle real-time validation errors from the card Element.
    card.addEventListener('change', function(event) {
        var displayError = document.getElementById('card-errors');
        if (event.error) {
            displayError.textContent = event.error.message;
        } else {
            displayError.textContent = '';
        }
    });

    // Handle form submission.
    var form = document.getElementById('payment-form');
    form.addEventListener('submit', function(event) {
    event.preventDefault();

    stripe.createToken(card).then(function(result) {
            if (result.error) {
            // Inform the user if there was an error.
            var errorElement = document.getElementById('card-errors');
            errorElement.textContent = result.error.message;
            } else {
            // Send the token to your server.
            stripeTokenHandler(result.token);
            }
        });
    });

    // Submit the form with the token ID.
    function stripeTokenHandler(token) {
        // Insert the token ID into the form so it gets submitted to the server
        var form = document.getElementById('payment-form');
        var hiddenInput = document.createElement('input');
        hiddenInput.setAttribute('type', 'hidden');
        hiddenInput.setAttribute('name', 'stripeToken');
        hiddenInput.setAttribute('value', token.id);
        form.appendChild(hiddenInput);

        // Submit the form
        form.submit();
    }
</script>

app/views/users/payout.html.erb
<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-8-tablet is-6-desktop is-6-widescreen">
                <p class="title has-text-centered">Méthode de paiement</p>

                <%= form_with url: update_payout_path, local: true do |f| %>
                    <div class="field">
                        <%= f.text_field :paypal, value: current_user.paypal, placeholder: "Votre adresse Paypal", class: "input" %>
                    </div>
                    <div class="field is-grouped is-grouped-centered">
                        <%= f.submit "Sauvegarder", class: "button is-primary" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</section>