config/routes.rb
Rails.application.routes.draw do
  get 'message/create'
  root 'pages#home'

  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show', as: 'users'
  get '/selling_orders', to: 'orders#selling_orders'
  get '/buying_orders', to: 'orders#buying_orders'
  get '/orders/:id', to: 'orders#show', as: 'order_detail'
  get '/all_requests', to: 'requests#list'
  get '/request_offers/:id', to: 'requests#offers', as: 'request_offers'
  get '/my_offers', to: 'requests#my_offers'
  get '/search', to: 'pages#search'
  get '/calendar', to: 'pages#calendar'
  get '/plans', to: 'pages#plans'
  get '/settings/payment', to: 'users#payment', as: 'settings_payment'
  get '/settings/payout', to: 'users#payout', as: 'settings_payout'
  get '/gigs/:id/checkout/:pricing_type', to: 'gigs#checkout', as: 'checkout'
  get '/earnings', to: 'users#earnings', as: 'earnings'
  get '/conversations', to: 'conversations#list', as: 'conversations'
  get '/conversations/:id', to: 'conversations#show', as: 'conversation_detail'
  
  post '/users/edit', to: 'users#update'
  post '/offers', to: 'offers#create'
  post '/reviews', to: 'reviews#create'
  post '/settings/payment', to: 'users#update_payment', as: 'update_payment'
  post '/settings/payout', to: 'users#update_payout', as: 'update_payout'
  post '/users/withdraw', to: 'users#withdraw', as: 'withdraw'
  post '/messages', to: 'messages#create'
  post '/comments', to: 'comments#create'
  post '/subscribe', to: 'subscriptions#subscribe'
  post '/webhook', to: 'subscriptions#webhook'

  put 'orders/:id/complete', to: 'orders#complete', as: 'complete_order'
  put '/offers/:id/accept', to: 'offers#accept', as: 'accept_offer'
  put '/offers/:id/reject', to: 'offers#reject', as: 'reject_offer'

  delete '/gigs/:id/deactivate', to: 'gigs#deactivate', as: 'deactivate_gig'
  delete '/users/remove_subscription', to: 'users#remove_subscription', as: 'remove_subscription'

  mount ActionCable.server => '/cable'

  resources :gigs do
    member do
      delete :delete_photo
      post :upload_photo
    end
    resources :orders, only: [:create]
  end

  resources :requests

  devise_for :users, 
              path: '', 
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :gig, required: false
  belongs_to :request, required: false

  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"

  has_many :reviews

  enum status: [:inprogress, :complete]
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :authenticate_user!
    before_action :is_authorised, only: [:show]

    def create
        gig = Gig.find(params[:gig_id])
        pricing = gig.pricings.find_by(pricing_type: params[:pricing_type])

        if (pricing && !gig.has_single_pricing) || (pricing && pricing.basic? && gig.has_single_pricing)
            if charge(gig, pricing)
                return redirect_to buying_orders_path
            end
        else
            flash[:alert] = 'Le prix est incorrect.'
        end

        return redirect_to request.referrer
    end

    def selling_orders
        @orders = current_user.selling_orders
    end

    def buying_orders
        @orders = current_user.buying_orders
    end

    def complete
        @order = Order.find(params[:id])

        if !@order.complete?
            if @order.complete!
                flash[:notice] = "Sauvé."
            else
                flash[:alert] = "Quelque chose n'a pas fonctionné."
            end

            redirect_to buying_orders_path
        end
    end

    def show
        @order = Order.find(params[:id])
        @gig = @order.gig_id ? Gig.find(@order.gig_id) : nil
        @request = @order.request_id ? Request.find(@order.request_id) : nil
        @comments = Comment.where(order_id: params[:id])
    end

    private

    def is_authorised
        redirect_to dashboard_path, alert: "Vous n'avez pas l'autorisation" unless Order.where("id = ? and (seller_id = ? or buyer_id = ?)", params[:id], current_user.id, current_user.id)
    end

    def charge(gig, pricing)

        subscription = Subsription.find_by_user_id(current_user.id)
        if subscription.present? && subscription.success?
          plan = Stripe::Plan.retrieve(subscription.plan_id)
          rate = plan.metadata.commission.to_f/100
        else
          rate = 10.0/100
        end

        amount = pricing.price * (rate + 1)

        order = gig.orders.new
        order.due_date = Date.today() + pricing.delivery_time.days
        order.title = gig.title
        order.seller_id = gig.user.id
        order.seller_name = gig.user.full_name
        order.buyer_id = current_user.id
        order.buyer_name = current_user.full_name
        order.amount = amount

        if params[:payment].blank?
            flash[:alert] = "Pas de paiement sélectionné"
            return false
        elsif params[:payment] == "system"
            if amount > current_user.wallet
                flash[:alert] = "Pas assez d'argent"
                return false
            else
                ActiveRecord::Base.transaction do 
                    current_user.update!(wallet: current_user.wallet - amount)
                    gig.user.update!(wallet: gig.user.wallet + pricing.price)
                    Transaction.create! status: Transaction.statuses[:approved],
                                        transaction_type: Transaction.transaction_types[:trans],
                                        source_type: Transaction.source_types[:system],
                                        buyer: current_user,
                                        seller: gig.user,
                                        amount: amount, 
                                        gig: gig
                    order.save
                end
                flash[:notice] = "Votre commande est créée avec succès"
                return true
            end
        else
            charge = Stripe::Charge.create({
                amount: (amount * 100).to_i,
                currency: 'eur',
                customer: current_user.stripe_id,
                source: params[:payment]
            })

            if charge.paid
                ActiveRecord::Base.transaction do 
                    gig.user.update!(wallet: gig.user.wallet + pricing.price)
                    Transaction.create! status: Transaction.statuses[:approved],
                                        transaction_type: Transaction.transaction_types[:trans],
                                        source_type: Transaction.source_types[:stripe],
                                        buyer: current_user,
                                        seller: gig.user,
                                        amount: amount, 
                                        gig: gig
                    order.save
                end
                flash[:notice] = "Votre commande est créée avec succès"
                return true
            end
            flash[:alert] = "Carte non valide"
            return false
        end

    rescue ActiveRecord::RecordInvalid
        flash[:alert] = "Quelque chose n'a pas fonctionné"
        return false
    end
end

app/views/orders/_comment.html.erb
<article class="media">
    <%= link_to users_path(comment.user) do %>
        <figure class="media-left">
            <p class="image is-64x64 avatar <%= comment.user.online? ? 'online' : 'offline' %>">
                <%= image_tag avatar_url(comment.user), class: "is-rounded" %>
            </p>
        </figure>
    <% end %>
    <div class="media-content">
        <div class="content">
            <p>
                <strong><%= comment.user.full_name %></strong>
                <small class="is-pulled-right"><%= time_ago_in_words(comment.created_at) %></small>
                <br>
                <%= comment.content %>
                <br>
            </p>
        </div>

        <% if comment.attachment_file.attached? %>
            <p>
                <%= link_to url_for(comment.attachment_file), 
                        class: "tag small is-warning m-t-20", 
                        download: "Attachment_#{comment.attachment_file.id}" do %>
                    <i class="fas fa-paperclip fa-lg p-r-5"></i> <%= comment.attachment_file.filename %>
                <% end %>
            </p>
        <% end %>
    </div>
</article>

app/views/orders/buying_orders.html.erb
<section class="section">
    <div class="container">
        <p class="title">Gérer mes achats</p>

        <table class="table is-fullwidth">
            <thead>
                <tr>
                    <th>Date</th>
                    <th class="th">Nom du vendeur</th>
                    <th class="th">Titre</th>
                    <th class="th">Date d'échéance</th>
                    <th class="th">Montant</th>
                    <th class="th">Statut</th>
                    <th class="th">Action</th>
                </tr>
            </thead>

            <tbody>
                <% if @orders.blank? %>
                    <tr>
                        <td colspan="7" class="has-text-centered"><h1>AUCUNE DONNEE</h1></td>
                    </tr>
                <% end %>
                <% @orders.each do |o| %>
                    <tr>
                        <td><%= o.created_at.strftime('%d %b %Y') %></td>
                        <td><%= o.seller_name %></td>
                        <td>
                            <%= link_to o.title, order_detail_path(o) %>
                        </td>
                        <td><%= o.due_date.strftime('%d %b %Y') %></td>
                        <td>€<%= o.amount %></td>
                        <td>
                            <span class="tag <%= 'is-warning' if o.inprogress? %> <%= 'is-success' if o.complete? %>">
                                <%= o.status.capitalize %>
                            </span>
                        </td>
                        <td>
                            <% if !o.complete? %>
                                <%= link_to 'Marquer comme terminé', complete_order_path(o), method: :put, class: "button is-small is-primary #{'is-hidden' if o.complete?}" %>
                            <% else %>
                                <a class="button is-small is-outlined is-danger toggle-modal" aria-control="<%= o.id %>">Rating</a>
                                <div class="modal" id="<%= o.id %>">
                                    <div class="modal-background">
                                    </div>
                                    <div class="modal-content">
                                        <div class="box">
                                            <%= form_for Review.new do |f| %>
                                              <%= f.hidden_field :order_id, value: o.id %>
                                              <div class="field">
                                                <div id="star_<%= o.id %>"></div>
                                              </div>
                                              <div class="field">
                                                <%= f.text_area :review, class: "textarea" %>
                                              </div>
                                              <a class="toggle-modal button is-light" aria-control="<%= o.id %>">Annuler</a>
                                              <%= f.submit "Ajouter un commentaire", class: "button is-danger" %>
                                            <% end %>
                                        </div>
                                    </div>
                                </div>
                            <% end %>
                            
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</section>

<script>
    $('.toggle-modal').on('click', (e) => {
        e.stopPropagation();
        e.preventDefault();

        var order_id = e.target.getAttribute('aria-control');
        $('#star_' + order_id).raty({
            path: 'assets/raty-js/lib/images',
            scoreName: 'review[stars]',
            score: 1
        });

        $('#star_' + order_id).raty('reload');
        $('#' + order_id).toggleClass('is-active');
    })
</script>

app/views/orders/selling_orders.html.erb
<section class="section">
    <div class="container">
        <p class="title">Gérer mes ventes</p>

        <table class="table is-fullwidth">
            <thead>
                <tr>
                    <th>Date</th>
                    <th class="th">Nom de l'acheteur</th>
                    <th class="th">Titre</th>
                    <th class="th">Date d'échéance</th>
                    <th class="th">Montant</th>
                    <th class="th">Statut</th>
                </tr>
            </thead>

            <tbody>
                <% if @orders.blank? %>
                    <tr>
                        <td colspan="6" class="has-text-centered"><h1>AUCUNE DONNEE</h1></td>
                    </tr>
                <% end %>
                <% @orders.each do |o| %>
                    <tr>
                        <td><%= o.created_at.strftime('%d %b %Y') %></td>
                        <td><%= o.buyer_name %></td>
                        <td>
                            <%= link_to o.title, order_detail_path(o) %>
                        </td>
                        <td><%= o.due_date.strftime('%d %b %Y') %></td>
                        <td>€<%= o.amount %></td>
                        <td>
                            <span class="tag <%= 'is-warning' if o.inprogress? %> <%= 'is-success' if o.complete? %>">
                                <%= o.status.capitalize %>
                            </span>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</section>

app/views/orders/show.html.erb
<section class="section" data-channel-subscribe="order" data-order-id="<%= @order.id %>">
    <div class="container">
        <div class="columns">

            <!-- LEFT SIDE -->
            <div class="column is-two-thirds">
                <p class="menu-label">
                    Commentaires sur votre commande
                </p>
                <hr>
                <div id="comment-list">
                    <% @comments.each do |c| %>
                        <%= render 'orders/comment', comment: c %>
                    <% end %>
                </div>
                <hr>

                <article class="media">
                    <%= link_to users_path(current_user) do %>
                        <figure class="media-left">
                            <p class="image is-64x64 avatar <%= current_user.online? ? 'online' : 'offline' %>">                            
                                <%= image_tag avatar_url(current_user), class: "is-rounded" %>
                            </p>
                        </figure>
                    <% end %>
                    <div class="media-content">
                        <%= form_with model: Comment.new, id: "new_comment" do |f| %>
                            <%= f.hidden_field :order_id, value: @order.id %>
                            <div class="field">
                                <%= f.text_area :content, class: "textarea", placeholder: "Type your comment" %>
                            </div>

                            <div class="field is-pulled-left">
                                <div class="file is-warning has-name">
                                    <label class="file-label">
                                        <%= f.file_field :attachment_file, class: "file-input" %>
                                        <span class="file-cta">
                                            <span class="file-label">Pièce jointe (facultatif)</span>
                                        </span>
                                        <span class="file-name" id="file-name">Aucun fichier sélectionné</span>
                                    </label>
                                </div>
                            </div>

                            <div class="field is-pulled-right">
                                <%= f.submit "Poster un commentaire", class: "button is-primary" %>                      
                            </div>
                        <% end %>
                    </div>
                </article>
            </div>

            <!-- RIGHT SIDE -->
            <div class="column">
                <div class="card">
                    <div class="card-image">                        
                        <figure class="image is-3by2">
                            <%= image_tag gig_cover(@gig) if @gig %>
                            <%= image_tag 'icon_default_image.png' if @request %>
                        </figure>
                    </div>
                    <div class="card-content">
                        <p>
                            <strong><%= @order.title %></strong>
                            <strong class="title is-4 is-pulled-right has-text-success">€<%= @order.amount %></strong>
                        </p>
                        <br>
                        <small>
                            <p>Vendeur : <%= @order.seller_name %></p>
                            <br>
                            <p>Commande : <%= @order.id %></p>
                            <br>
                            <p><%= @order.created_at.strftime('%d, %b %Y') %></p>  
                        </small>                    
                    </div>                   
                </div>
            </div>

        </div>
    </div>
</section>

<script>
    $(document).ready(function() {
        var file = $('.file-input');
        file.change(function (e) {
            if (file[0].files.length > 0) {
                var attachment = file[0].files[0];
                $('.file-name').text(attachment.name + " (" + attachment.size + " bytes)");
            }
        })
    })
</script>