config/routes.rb
Rails.application.routes.draw do
  get 'message/create'
  root 'pages#home'

  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show', as: 'users'
  get '/selling_orders', to: 'orders#selling_orders'
  get '/buying_orders', to: 'orders#buying_orders'
  get '/orders/:id', to: 'orders#show', as: 'order_detail'
  get '/all_requests', to: 'requests#list'
  get '/request_offers/:id', to: 'requests#offers', as: 'request_offers'
  get '/my_offers', to: 'requests#my_offers'
  get '/search', to: 'pages#search'
  get '/calendar', to: 'pages#calendar'
  get '/plans', to: 'pages#plans'
  get '/settings/payment', to: 'users#payment', as: 'settings_payment'
  get '/settings/payout', to: 'users#payout', as: 'settings_payout'
  get '/gigs/:id/checkout/:pricing_type', to: 'gigs#checkout', as: 'checkout'
  get '/earnings', to: 'users#earnings', as: 'earnings'
  get '/conversations', to: 'conversations#list', as: 'conversations'
  get '/conversations/:id', to: 'conversations#show', as: 'conversation_detail'
  
  post '/users/edit', to: 'users#update'
  post '/offers', to: 'offers#create'
  post '/reviews', to: 'reviews#create'
  post '/settings/payment', to: 'users#update_payment', as: 'update_payment'
  post '/settings/payout', to: 'users#update_payout', as: 'update_payout'
  post '/users/withdraw', to: 'users#withdraw', as: 'withdraw'
  post '/messages', to: 'messages#create'
  post '/comments', to: 'comments#create'
  post '/subscribe', to: 'subscriptions#subscribe'
  post '/webhook', to: 'subscriptions#webhook'

  put 'orders/:id/complete', to: 'orders#complete', as: 'complete_order'
  put '/offers/:id/accept', to: 'offers#accept', as: 'accept_offer'
  put '/offers/:id/reject', to: 'offers#reject', as: 'reject_offer'

  delete '/gigs/:id/deactivate', to: 'gigs#deactivate', as: 'deactivate_gig'
  delete '/users/remove_subscription', to: 'users#remove_subscription', as: 'remove_subscription'

  mount ActionCable.server => '/cable'

  resources :gigs do
    member do
      delete :delete_photo
      post :upload_photo
    end
    resources :orders, only: [:create]
  end

  resources :requests

  devise_for :users, 
              path: '', 
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :gigs
    has_many :requests
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :order
  has_one_attached :attachment_file
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"

  def last_message
    message = Message.where(conversation_id: self.id).last
    if message.present?
      return message
    else
      return Message.new updated_at: Time.now
    end
  end
end

app/models/gig.rb
class Gig < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :pricings
  has_many :orders
  has_many :reviews
  has_many_attached :photos
  has_rich_text :description

  accepts_nested_attributes_for :pricings

  validates :title, presence: {message: 'Cannot be blank'}

  def average_rating
    reviews.count == 0 ? 0 : reviews.average(:stars).round(1)
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :request
  belongs_to :user

  enum status: [:pending, :accepted, :rejected]
  validates :amount, :days, numericality: { only_integer: true, message: "must be a number"}
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :gig, required: false
  belongs_to :request, required: false

  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"

  has_many :reviews

  enum status: [:inprogress, :complete]
end

app/models/pricing.rb
class Pricing < ApplicationRecord
  belongs_to :gig
  enum pricing_type: [:basic, :standard, :premium]
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_one_attached :attachment_file
  has_many :offers, dependent: :delete_all
  has_many :orders

  validates :title, presence: { message: "cannot be empty"}
  validates :description, presence: { message: "cannot be empty"}
  validates :delivery, numericality: { only_integer: true, message: "must be a number"}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :order
  belongs_to :gig, required: false
  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"
end

app/models/subsription.rb
class Subsription < ApplicationRecord
    belongs_to :user
    enum status: [:pending, :success]
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    belongs_to :buyer, class_name: "User", optional: true
    belongs_to :seller, class_name: "User", optional: true
    belongs_to :gig, optional: true
    belongs_to :request, optional: true

    enum status: [:approved, :pending, :rejected]
    enum transaction_type: [:trans, :withdraw]
    enum source_type: [:system, :stripe]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_one_attached :avatar
  has_many :gigs
  has_many :requests
  has_many :offers
  
  has_many :buying_orders, foreign_key: "buyer_id", class_name: "Order"
  has_many :selling_orders, foreign_key: "seller_id", class_name: "Order"

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :lastseenable

  validates :full_name, presence: true, length: {maximum: 50}

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first

    if user 
      if !user.provider
        user.update(uid: auth.uid, provider: auth.provider, image: auth.info.image)
      end
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.full_name = auth.info.name   # assuming the user model has a name
        user.image = auth.info.image # assuming the user model has an image

        user.uid = auth.uid
        user.provider = auth.provider
      end
    end
  end

  def online?
    return !last_seen.nil? && ((last_seen + 10.minutes) > Time.now)
  end
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/dashboard/index.html.erb
<div class="main-content-are">
    <div class="main-content-container">
        <div class="main-content">
            <div class="row">

                <div class="col-md-3 bg-primary">
                    <div class="card text-white text-center">
                        <h1><%= @user_count %></h1>
                        <p>Users</p>
                    </div>
                </div>

                <div class="col-md-3 bg-warning">
                    <div class="card text-white text-center">
                        <h1><%= @gig_count %></h1>
                        <p>Services</p>
                    </div>
                </div>

                <div class="col-md-3 bg-success">
                    <div class="card text-white text-center">
                        <h1><%= @order_count %></h1>
                        <p>Commandes</p>
                    </div>
                </div>

                <div class="col-md-3 bg-info">
                    <div class="card text-white text-center">
                        <h1><%= @categories_count %></h1>
                        <p>Categories</p>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loire-Connect - Freelances en Loire-Atlantique (44)</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>

    <%= favicon_link_tag asset_path('favicon.ico') %>

    <% if content_for?(:head)  %>
      <%= yield(:head) %>
    <% end %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/notification' %>

    <%= yield %>
  </body>
</html>

app/views/pages/calendar.html.erb
<section class="section">
    <div class="container m-t-20">
        <div id="calendar"></div>
    </div>
</section>

<script>
    orders = <%= raw @orders.to_json %>;

    function showOrders(orders) {
        return orders.map(function(o){
            let code = '#ffdd57';

            if (new Date(o.due_date) < new Date()) {
                code = '#ff3860';
            } else if (new Date(o.due_date) > new Date(new Date().getTime() + (2*24*60*60*1000))) {
                code = '#23d160';
            }

            return {
                id: o.id, 
                title: o.buyer_name,
                start: o.due_date,
                end: o.due_date,
                backgroundColor: code
            }
        })
    }

    var getQueryParam = function(param) {
        var found, item = window.location.search.substr(1).split('=');

        if (param == item[0]) {
            found = item[1];
        }
        return found;
    }

    $(function() {
        var start_date = getQueryParam("start_date") ? new Date(getQueryParam("start_date")) : new Date();
        var calendarEl = document.getElementById('calendar');
        var calendar = new Calendar(calendarEl, {
            header: {
                left: 'prev,next',
                right: 'dayGridMonth,listMonth'
            },
            defaultDate: start_date,
            plugins: [DayGridPlugin, ListPlugin],
            events: showOrders(orders),
            eventClick: function(info) {
                window.location.href= "/orders/" + info.event.id;
            },
            defaultView: 'dayGridMonth'
        });

        calendar.render();

        $('.fc-prev-button').on('click', function() {
            window.location.search = 'start_date=' + calendar.state.currentDate.toISOString().split("T")[0];
        });

        $('.fc-next-button').on('click', function() {
            window.location.search = 'start_date=' + calendar.state.currentDate.toISOString().split("T")[0];
        });
    })
</script>

app/views/pages/home.html.erb
<% content_for :head do %>
    <meta name="turbolinks-cache-control" content="no-cache"> 
<% end %>

<section class="hero is-medium has-bg-img">
    <div class="hero-body">
        <div class="container">
            <h1 class="title has-text-white">
                Trouver les services d'un freelance<br>
                en Loire-Atlantique (44)
            </h1>
            <%= form_tag search_path, method: :get, class: "field has-addons" do %>
                <div class="control has-icons-left">
                    <span class="icon is-small is-left">
                        <i class="fa fa-search"></i>
                    </span>
                    <%= text_field_tag 'q', '', class: "input", placeholder: "Essayer 'logo'" %>
                </div>
                <div class="control">
                    <button class="button is-primary" type="submit">Rechercher</button>
                </div>
            <% end %>
        </div>
    </div>
</section>

<section class="m-t-100">
    <div class="container">
        <h1 class="title is-4 p-l-10">Services populaires</h1>
        <div id="carousel-category" class="hero-carousel">

            <div class="carousel-item">
                <div class="p-10">
                    <%= link_to search_path(category: 1) do %>
                        <div class="card-image">
                            <%= image_tag 'home/category_4.jpg', class: 'is-background', width: "100%", height: "100%" %>
                            <div class="card-content is-overlay is-clipped">
                                <span class="subtitle f-15 has-text-white">Développer votre activité</span><br>
                                <span class="title is-4 has-text-white">Site vitrine</span>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>

            <div class="carousel-item">
                <div class="p-10">
                    <%= link_to search_path(category: 2) do %>
                        <div class="card-image">
                            <%= image_tag 'home/category_3.jpg', class: 'is-background', width: "100%", height: "100%" %>
                            <div class="card-content is-overlay is-clipped">
                                <span class="subtitle f-15 has-text-white">Créer votre marque</span><br>
                                <span class="title is-4 has-text-white">Logo</span>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>

            <div class="carousel-item">
                <div class="p-10">
                    <%= link_to search_path(category: 3) do %>
                        <div class="card-image">
                            <%= image_tag 'home/category_5.jpg', class: 'is-background', width: "100%", height: "100%" %>
                            <div class="card-content is-overlay is-clipped">
                                <span class="subtitle f-15 has-text-white">Améliorer votre présence en ligne</span><br>
                                <span class="title is-4 has-text-white">Réseaux sociaux</span>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>

            <div class="carousel-item">
                <div class="p-10">
                    <%= link_to search_path(category: 4) do %>
                        <div class="card-image">
                            <%= image_tag 'home/category_2.jpg', class: 'is-background', width: "100%", height: "100%" %>
                            <div class="card-content is-overlay is-clipped">
                                <span class="subtitle f-15 has-text-white">Vendre sur Internet</span><br>
                                <span class="title is-4 has-text-white">Site E-commerce</span>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>

            <div class="carousel-item">
                <div class="p-10">
                    <%= link_to search_path(category: 5) do %>
                        <div class="card-image">
                            <%= image_tag 'home/category_6.jpg', class: 'is-background', width: "100%", height: "100%" %>
                            <div class="card-content is-overlay is-clipped">
                                <span class="subtitle f-15 has-text-white">Accroitre votre attractivité</span><br>
                                <span class="title is-4 has-text-white">Campagne publicitaire</span>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>

        </div>
    </div>
</section>

<script>
    BulmaCarousel.attach("#carousel-category", {
        slidesToScroll: 1,
        slidesToShow: 4,
        infinite: false,
        pagination: false
    });
</script>

app/views/pages/plans.html.erb
<section class="section">
    <div class="container">
        <p class="title is-4 m-t-50 m-b-50 has-text-centered">
            Choisissez le meilleur forfait pour votre entreprise
        </p>

        <div class="pricing-table m-t-20 m-l-50 m-r-50">
            <% @plans.data.each do |plan| %>
                <div class="pricing-plan
                    <%= 'is-warning' if plan.amount == 500 %>
                    <%= 'is-primary is-active' if plan.amount == 1000 %>
                    <%= 'is-danger' if plan.amount == 2500 %>
                    ">
                    <div class="plan-header"><%= plan.nickname %></div>
                    <div class="plan-price">
                        <span class="plan-price-amount">
                            <span class="plan-price currency">€</span><%= plan.amount / 100 %>
                        </span>/ mois
                    </div>
                    <div class="plan-items">
                        <div class="plan-item">
                            La commission est de <%= plan.metadata.commission %>%
                        </div>
                    </div>
                    <div class="plan-footer">
                        <%= form_with url: subscribe_url do |f| %>
                            <%= f.hidden_field :plan_id, value: plan.id %>
                            <%= f.submit "Choisir", class: "button is-fullwidth" %>
                        <% end %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</section>

app/views/shared/_categories.html.erb
<nav class="navbar has-shadow" style="z-index: 5">
    <div class="container">
        <div class="navbar">
            <% @categories.each do |item| %>
              <%= link_to "#{item.name}", search_path(category: item.id), class: "navbar-item" %>
            <% end %>
        </div>
    </div>
</nav>

app/views/shared/_gigs.html.erb
<% @gigs.each do |gig| %>

<div class="column is-one-third">
    <div class="card">

        <div class="card-image">
            <%= link_to gig_path(gig) do %>
                <figure class="image is-4by3">
                    <%= image_tag gig_cover(gig) %>
                </figure>
            <% end %>
        </div>

        <div class="card-content p-t-5 p-b-5">
            <p class="subtitle is-6 m-b-5"><%= link_to gig.title.truncate(100), gig_path(gig) %></p>
            <span class="star-review"><i class="fa fa-star"></i>
                <%= gig.average_rating %> 
                <span class="has-text-primary">(<%= gig.reviews.count %>)</span>
            </span>                                        
        </div>

        <footer class="card-footer">
            <span class="card-footer-item">
                <%= link_to users_path(gig.user) do %>
                    <figure class="image is-32x32 avatar <%= gig.user.online? ? 'online' : 'offline' %>">
                        <%= image_tag avatar_url(gig.user), class: "is-rounded" %>
                    </figure>
                <% end %>
            </span>
            <a class="has-text-danger is-block card-footer-item has-text-right">
                    <span class="small-title">A PARTIR DE</span> 
                    <strong><%= gig.price %>€</strong>  
            </a>
        </footer>  
        
    </div>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar" style="background-color: #E3E2DD" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="/">
            <%= image_tag 'loireconnect.png', class: 'is-background' %>
            &nbsp;&nbsp;&nbsp;<h1 class="title is-4">Loire-Connect</h1>
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                <div class="navbar-item">
                    <%= form_tag search_path, method: :get do %>
                        <div class="field has-addons <%= 'is-hidden' if current_page?(root_path) %>">
                            <div class="control has-icons-left">
                                <span class="icon is-small is-left">
                                    <i class="fa fa-search"></i>
                                </span>
                                <%= text_field_tag 'q', '', class: "input", placeholder: "Essayer 'logo'" %>
                            </div>
                            <div class="control">
                                <button class="button is-danger" type="submit">Rechercher</button>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
            <div class="navbar-end">
                <%= link_to "Tarifs", plans_path, class: "navbar-item" %>
                <%= link_to "Poster un service", new_gig_path, class: "navbar-item" %>
                <%= link_to "Parcourir les services", search_path, class: "navbar-item" %>

                <% if (!user_signed_in?) %>
                    <div class="navbar-item">
                        <div class="buttons">
                            <%= link_to 'S\'inscrire', new_user_registration_path, class: "button is-primary" %>
                            <%= link_to 'Se connecter', new_user_session_path, class: "button is-light" %>
                        </div>
                    </div>
                <% else %>
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link">
                            <figure class="image is-24x24 m-r-5 avatar <%= current_user.online? ? 'online' : 'offline' %>">
                                <%= image_tag avatar_url(current_user), class: "is-rounded" %>
                            </figure>
                            <%= current_user.full_name %>
                        </a>

                        <div class="navbar-dropdown">
                            <%= link_to 'Profil', edit_user_registration_path, class: "navbar-item" %>
                            <%= link_to 'Tableau de bord', dashboard_path, class: "navbar-item" %>
                            <hr class="navbar-divider">
                            <%= link_to 'Déconnexion', destroy_user_session_path, method: :delete, class: "navbar-item" %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</nav>


<% if (user_signed_in?) && !current_page?(root_path) && !current_page?(plans_path) && !current_page?(search_path) && !current_page?("/gigs/#{params[:id]}") && !current_page?("/users/#{params[:id]}") %>
    <nav class="navbar has-shadow" style="z-index: 5">
        <div class="container">
            <div class="navbar">
                <%= link_to 'Tableau de bord', dashboard_path, class: 'navbar-item' %>
                <!--%= link_to 'Calendrier', calendar_path, class: 'navbar-item' %-->

                <!--div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Vendre</a>
                    <div class="navbar-dropdown">
                        <%= link_to "Poster un service", new_gig_path, class: "navbar-item" %>
                    </div>
                </!--div-->

                <!--div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Acheter</a>
                    <div class="navbar-dropdown">
                        <%= link_to "Créer une demande", new_request_path, class: "navbar-item" %>
                        <%= link_to "Gérer les demandes", requests_path, class: "navbar-item" %>
                    </div>
                </!--div-->

                <!--div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Requêtes d'acheteurs</a>
                    <div class="navbar-dropdown">
                        <%= link_to "Requêtes actives", all_requests_path, class: "navbar-item" %>
                        <%= link_to "Offres envoyées", my_offers_path, class: "navbar-item" %>
                    </div>
                </!--div-->

                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Commandes</a>
                    <div class="navbar-dropdown">
                        <%= link_to 'Ventes', selling_orders_path, class: "navbar-item" %>
                        <%= link_to 'Achats', buying_orders_path, class: "navbar-item" %>
                    </div>
                </div>

                <%= link_to 'Revenus', earnings_path, class: 'navbar-item' %>
                <%= link_to 'Messages', conversations_path, class: 'navbar-item' %>

                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Paramètres</a>
                    <div class="navbar-dropdown">
                        <%= link_to 'Mode de paiement', settings_payment_path, class: 'navbar-item' %>
                        <%= link_to 'Méthode de paiement', settings_payout_path, class: 'navbar-item' %>
                    </div>
                </div>
            </div>
        </div>
    </nav>
<% end %>

<script>
$(document).ready(function() {

  // Check for click events on the navbar burger icon
  $(".navbar-burger").click(function() {

      // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
      $(".navbar-burger").toggleClass("is-active");
      $(".navbar-menu").toggleClass("is-active");

  });
});
</script>

app/views/shared/_notification.html.erb
<% unless flash.empty? %>
  <script>
    <% flash.each do |key, value| %>
        <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
        new Noty({
            type: '<%= type %>',
            layout: 'topRight',
            timeout: '3000',
            theme: 'sunset',
            text: '<%= value %>'
        }).show();
    <% end %>
  </script>
<% end %>